# Generated by Django 4.2.1 on 2023-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_f_name_remove_student_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
