# Generated by Django 4.2.1 on 2023-05-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_login_alter_student_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='passwords',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='usernames',
        ),
    ]
